### ISSUE TITLE
RoutingError (No route matches [GET] "/plugin_assets/open_flash_chart/javascripts/swfobject.js")

### ISSUE THREAD

**Issue by plapczyn** [pharmazone/redmine_charts2#32]
I am getting routing error finding open_flash_chart.  Not sure what's going on.

_Here are my settings:_

<pre>
Bitnami Redmine Linux Stack 2.3.1-0
Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_charts2                          0.2.1
  redmine_graphs                           0.1.0
</pre>

_Log file except:_

<pre>
Started GET "/redmine/plugin_assets/open_flash_chart/javascripts/swfobject.js" for xx.xx.xx.xx at 2013-05-18 11:19:01 -0400

ActionController::RoutingError (No route matches [GET] "/plugin_assets/open_flash_chart/javascripts/swfobject.js"):
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/builder.rb:134:in `call'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  passenger (4.0.0.rc6) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.0.rc6) lib/phusion_passenger/request_handler/thread_handler.rb:135:in `accept_and_process_next_request'
  passenger (4.0.0.rc6) lib/phusion_passenger/request_handler/thread_handler.rb:106:in `main_loop'
  passenger (4.0.0.rc6) lib/phusion_passenger/request_handler.rb:458:in `block (4 levels) in start_threads'
  passenger (4.0.0.rc6) lib/phusion_passenger/utils/robust_interruption.rb:102:in `disable_interruptions'
  passenger (4.0.0.rc6) lib/phusion_passenger/request_handler.rb:453:in `block (3 levels) in start_threads'

</pre>

**Comment by jurrack** [comment]
rake redmine:plugins:assets

**Comment by pharmazone** [comment]
Wdym?
