### ISSUE TITLE
No graphs display

### ISSUE THREAD

**Issue by fengyedou** [pharmazone/redmine_charts2#47]
I installed on redmine 2.3.2, I click to the chart2 provided graphs, no graph is shown.

**Comment by liomoura** [comment]
I have same problem, but a I installed on redmine 2.6.2

1. Have you enable plugin for your project?
Yes.
2. Does logs contain any messages related to redmine charts?
No, redmine displays no error in 'production.log'.

Thank you!

**Comment by pharmazone** [comment]
I've setup Redmine(2.6.5) with plugin(branch `redmine21`).

Everything is working.
Show your screenshots from Charts tab.


![burndown](https://cloud.githubusercontent.com/assets/138582/7656684/54d2316c-fb2c-11e4-9eb0-d7d09b3d187a.png)
![burndownvelocity](https://cloud.githubusercontent.com/assets/138582/7656685/54fb7626-fb2c-11e4-897c-162b8c9db58d.png)
![info](https://cloud.githubusercontent.com/assets/138582/7656689/54fec420-fb2c-11e4-8c36-4ad82097c15e.png)
![issues](https://cloud.githubusercontent.com/assets/138582/7656688/54fdb620-fb2c-11e4-8059-a777994106e2.png)
![loggedhours](https://cloud.githubusercontent.com/assets/138582/7656687/54fdaee6-fb2c-11e4-8ab9-da67f98c2db4.png)
![plugins](https://cloud.githubusercontent.com/assets/138582/7656686/54fc0de8-fb2c-11e4-93f3-7a38c0ad254e.png)

**Comment by liomoura** [comment]
Hello,

now found the error logged in 'production.log', which is probably the cause of the problem!

ActionController::RoutingError (No route matches [GET] "/plugin_assets/open_flash_chart/javascripts/swfobject.js"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:82:in `block in pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in `catch'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in `pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:55:in `process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:41:in `receive_data'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in `run_machine'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in `run'
  thin-1.6.1-x86 (mingw32) lib/thin/backends/base.rb:73:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/server.rb:162:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/controllers/controller.rb:87:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:200:in `run_command'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:156:in `run!'
  thin-1.6.1-x86 (mingw32) bin/thin:6:in `<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in `<main>'

**Comment by pharmazone** [comment]
Do you have this file in
"public/plugin_assets/open_flash_chart/javascripts/swfobject.js"?



--
Alexey S. Mirniy

**Comment by liomoura** [comment]
wow! worked !!!

I had not copied all assests files, sorry.

thank you so much for your help and congratulations for the work done

**Comment by pharmazone** [comment]
I think the only thing that you had to done it is restart Redmine server.

In production environment rails does not process any changes and updates.

Have a good weekend!
